### ISSUE TITLE
Folder mapped pages not being redirected by redirect.xlsx

### ISSUE THREAD

**Issue by vhargrave** [adobe/helix-html-pipeline#296] opened 2023-04-17 14:00 UTC
**Description**
In the express project we have folder mapped pages that are defined in our [fstab.yaml](https://github.com/adobe/express-website/blob/main/fstab.yaml) file. This means that when trying to access a link under /express/templates/ we load a default word page. This word page then requests content from a json and loads its content in from there. 
Here's an example of one these pages - https://www.adobe.com/express/templates/flyer/christmas
We've defined redirects some of these pages in our redirect.xlsx file, but the redirects don't seem to work. An example of a page that should be redirected is https://www.adobe.com/express/templates/advertisement
Instead of being redirected though, the page is 404ing

**Expected behavior**
The redirect defined in the redirect.xlsx file should work

**Additional context**
This issue was discussed in this slack thread - https://adobe-mwp.slack.com/archives/C9KD0TT6G/p1681398155073459

**Comment by tripodsan** [comment] 2023-05-05 09:22
this is caused by #30 and will be fixed with #307

**Closed** 2023-05-31 08:18 UTC
Labels: bug
